import Link from 'next/link';
import Sidebar from '@/components/shell/sidebar';
import Topbar from '@/components/shell/topbar';
import PageHeader from '@/components/shell/page-header';
import Panel from '@/components/ui/panel';
import Badge from '@/components/ui/badge';
import EmptyValue from '@/components/ui/empty-value';
import { requireAdmin } from '@/lib/auth';
import { getForecastResults, getForecastRuns } from '@/lib/scm';
import { runBaselineForecastAction } from '@/lib/forecast-engine';

export default async function ForecastRunsPage({ searchParams }: { searchParams: Promise<Record<string, string | undefined>> }) {
  await requireAdmin('/admin/forecast-runs');
  const params = await searchParams;
  const [{ rows, error }, result] = await Promise.all([getForecastRuns(), getForecastResults(params.run)]);
  return <div className="app-shell"><Sidebar role="ADMIN" /><main className="main"><Topbar title="Forecast 실행 이력" subtitle="FORECAST RUNS" /><div className="content"><PageHeader eyebrow="ADMIN / FORECAST" title="Forecast 실행 이력" description="저장된 모델 결과를 조회합니다. 화면 조회 시 Forecast를 재실행하지 않습니다." /><form action={runBaselineForecastAction}><button className="button primary" type="submit">Baseline Forecast 실행</button></form>{params.error && <p className="text-danger" role="alert">실행 실패: {params.error}</p>}{error ? <p className="text-danger">실행 이력 조회에 실패했습니다: {error}</p> : <Panel title="Forecast Runs"><div className="analysis-table-wrap"><table className="analysis-table"><thead><tr><th>Run ID</th><th>상태</th><th>실행 시간</th><th>모델 수</th><th>SKU 수</th><th>결과 행</th><th>Data Snapshot</th><th>Stale</th><th>실행자</th></tr></thead><tbody>{rows.map((run) => <tr key={run.runId}><td><Link href={`/admin/forecast-runs?run=${run.runId}`}>{run.runId.slice(0, 8)}…</Link></td><td><Badge status={run.status === 'SUCCESS' ? 'SAFE' : run.status === 'FAILED' ? 'CRITICAL' : 'WARNING'}>{run.status}</Badge></td><td>{run.startedAt ? new Date(run.startedAt).toLocaleString('ko-KR') : <EmptyValue reasonCode="NO_START_TIME" />}</td><td>{run.nModels ?? <EmptyValue reasonCode="NO_MODEL_COUNT" />}</td><td>{run.nItems ?? <EmptyValue reasonCode="NO_ITEM_COUNT" />}</td><td>{run.nRows ?? <EmptyValue reasonCode="NO_RESULT_COUNT" />}</td><td>{run.dataSnapshotAt ? new Date(run.dataSnapshotAt).toLocaleString('ko-KR') : <EmptyValue reasonCode="NO_SNAPSHOT" />}</td><td><Badge status={run.stale ? 'WARNING' : 'SAFE'}>{run.stale ? 'STALE' : 'FRESH'}</Badge></td><td>{run.triggeredEmail ?? <EmptyValue reasonCode="NO_TRIGGER_USER" />}</td></tr>)}{rows.length === 0 && <tr><td colSpan={9}><EmptyValue reasonCode="NO_FORECAST_RUN" /></td></tr>}</tbody></table></div></Panel>}{params.run && <Panel title="선택한 Forecast 결과" description={`run_id: ${params.run}`}><div className="analysis-table-wrap"><table className="analysis-table"><thead><tr><th>모델</th><th>SKU</th><th>기간</th><th>P50</th><th>P80</th><th>P90</th><th>Sigma</th><th>Basis</th></tr></thead><tbody>{result.rows.map((row) => <tr key={`${row.modelId}-${row.itemId}-${row.period}`}><td>{row.modelId}</td><td>{row.itemId}</td><td>{row.period}</td><td>{row.p50 ?? <EmptyValue reasonCode={row.reasonCode ?? 'P50_UNAVAILABLE'} />}</td><td>{row.p80 ?? <EmptyValue reasonCode={row.reasonCode ?? 'P80_UNAVAILABLE'} />}</td><td>{row.p90 ?? <EmptyValue reasonCode={row.reasonCode ?? 'P90_UNAVAILABLE'} />}</td><td>{row.sigma ?? <EmptyValue reasonCode="SIGMA_UNAVAILABLE" />}</td><td>{row.basis}</td></tr>)}{result.rows.length === 0 && <tr><td colSpan={8}><EmptyValue reasonCode="NO_FORECAST_RESULT" /></td></tr>}</tbody></table></div></Panel>}</div></main></div>;
}
