create schema if not exists core;

create table if not exists core.app_user (
  user_id uuid primary key references auth.users(id) on delete cascade,
  email text not null unique,
  name text not null default '',
  department text not null default '',
  role text not null default 'USER' check (role in ('ADMIN', 'USER')),
  active boolean not null default true,
  last_login_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists core.audit_log (
  id bigint generated by default as identity primary key,
  actor uuid references auth.users(id) on delete set null,
  action text not null,
  target_type text not null,
  target_id text not null,
  before jsonb,
  after jsonb,
  at timestamptz not null default now()
);

create index if not exists app_user_role_active_idx on core.app_user(role, active);
create index if not exists audit_log_target_idx on core.audit_log(target_type, target_id, at desc);

create or replace function core.set_app_user_updated_at()
returns trigger
language plpgsql
security invoker
set search_path = core, public
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists app_user_set_updated_at on core.app_user;
create trigger app_user_set_updated_at before update on core.app_user
for each row execute function core.set_app_user_updated_at();

create or replace function public.handle_new_auth_user()
returns trigger
language plpgsql
security definer
set search_path = public, core
as $$
begin
  insert into core.app_user (user_id, email, name)
  values (new.id, coalesce(new.email, ''), coalesce(new.raw_user_meta_data ->> 'name', ''))
  on conflict (user_id) do update set email = excluded.email, updated_at = now();
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created after insert on auth.users
for each row execute function public.handle_new_auth_user();

create or replace function core.is_admin(check_user_id uuid default auth.uid())
returns boolean
language sql
stable
security definer
set search_path = core, public
as $$
  select exists (
    select 1 from core.app_user
    where user_id = check_user_id and role = 'ADMIN' and active = true
  );
$$;

create or replace function core.admin_update_app_user(
  target_user_id uuid,
  next_role text,
  next_active boolean
)
returns core.app_user
language plpgsql
security definer
set search_path = core, public
as $$
declare
  actor_id uuid := auth.uid();
  existing_user core.app_user;
  changed_user core.app_user;
begin
  if actor_id is null or not core.is_admin(actor_id) then
    raise exception 'ADMIN_REQUIRED' using errcode = '42501';
  end if;
  if next_role not in ('ADMIN', 'USER') then
    raise exception 'INVALID_ROLE' using errcode = '22023';
  end if;

  select * into existing_user from core.app_user where user_id = target_user_id for update;
  if existing_user.user_id is null then
    raise exception 'USER_NOT_FOUND' using errcode = 'P0002';
  end if;
  if target_user_id = actor_id and (next_role <> 'ADMIN' or next_active = false) then
    raise exception 'SELF_ADMIN_LOCKOUT' using errcode = '42501';
  end if;

  update core.app_user
  set role = next_role, active = next_active
  where user_id = target_user_id
  returning * into changed_user;

  if existing_user.role <> changed_user.role then
    insert into core.audit_log(actor, action, target_type, target_id, before, after)
    values (actor_id, 'USER_ROLE_CHANGED', 'app_user', target_user_id::text,
      jsonb_build_object('role', existing_user.role),
      jsonb_build_object('role', changed_user.role));
  end if;
  if existing_user.active <> changed_user.active then
    insert into core.audit_log(actor, action, target_type, target_id, before, after)
    values (actor_id, case when changed_user.active then 'USER_ACTIVATED' else 'USER_DEACTIVATED' end,
      'app_user', target_user_id::text,
      jsonb_build_object('active', existing_user.active),
      jsonb_build_object('active', changed_user.active));
  end if;
  return changed_user;
end;
$$;

create or replace function core.touch_last_login()
returns void
language sql
security definer
set search_path = core, public
as $$
  update core.app_user set last_login_at = now() where user_id = auth.uid() and active = true;
$$;

revoke all on schema core from anon;
revoke all on all tables in schema core from anon;
revoke all on all sequences in schema core from anon;
revoke all on all tables in schema analytics from anon;
revoke all on schema raw from anon;
revoke all on all tables in schema raw from anon;
grant usage on schema core to authenticated;
grant usage on schema analytics to authenticated;
grant select on all tables in schema analytics to authenticated;
grant select on core.app_user to authenticated;
grant select on core.audit_log to authenticated;
grant select on core.leadtime_plan, core.usage_profile to authenticated;
grant execute on function core.is_admin(uuid) to authenticated;
grant execute on function core.admin_update_app_user(uuid, text, boolean) to authenticated;
grant execute on function core.touch_last_login() to authenticated;

alter default privileges in schema core revoke all on tables from anon;
alter default privileges in schema analytics revoke all on tables from anon;
alter default privileges in schema raw revoke all on tables from anon;
alter default privileges in schema analytics grant select on tables to authenticated;

alter table core.app_user enable row level security;
alter table core.audit_log enable row level security;

drop policy if exists "사용자 본인 또는 관리자 조회" on core.app_user;
create policy "사용자 본인 또는 관리자 조회" on core.app_user
for select to authenticated
using (user_id = auth.uid() or core.is_admin());

drop policy if exists "관리자 감사 로그 조회" on core.audit_log;
create policy "관리자 감사 로그 조회" on core.audit_log
for select to authenticated
using (core.is_admin());

drop policy if exists "인증 사용자 분석 조회" on core.leadtime_plan;
drop policy if exists "인증 사용자 분석 조회" on core.usage_profile;
create policy "인증 사용자 분석 조회" on core.leadtime_plan for select to authenticated using (auth.uid() is not null);
create policy "인증 사용자 분석 조회" on core.usage_profile for select to authenticated using (auth.uid() is not null);

drop policy if exists "관리자 리드타임 변경" on core.leadtime_plan;
drop policy if exists "관리자 사용량 변경" on core.usage_profile;
create policy "관리자 리드타임 변경" on core.leadtime_plan for all to authenticated using (core.is_admin()) with check (core.is_admin());
create policy "관리자 사용량 변경" on core.usage_profile for all to authenticated using (core.is_admin()) with check (core.is_admin());
